name: Contact-manager CI/CD

on:
  push:
    branches: [ "main" ] # or your deployment branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS App
        run: npm run build

      - name: Run tests
        run: npm run test
